package com.rssmonitor;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

public class DigestGenerator {
    private static final Logger logger = LoggerFactory.getLogger(DigestGenerator.class);
    
    private static final DateTimeFormatter DATE_FORMATTER = 
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm").withZone(ZoneId.systemDefault());
    
    public String generate(List<Article> rankedArticles, String summary) {
        StringBuilder digest = new StringBuilder();
        
        // Header
        digest.append("🔥 Tech Digest | 科技摘要\n\n");
        digest.append("Generated: ").append(DATE_FORMATTER.format(java.time.Instant.now())).append("\n\n");
        
        // Summary section
        digest.append("## Summary | 摘要\n\n");
        digest.append(escapeHtml(summary));
        digest.append("\n\n");
        
        // Trending articles section
        digest.append("## Trending Articles | 热门文章\n\n");
        
        if (rankedArticles.isEmpty()) {
            digest.append("No new trending articles found.\n\n未找到新的热门文章。\n");
        } else {
            for (int i = 0; i < rankedArticles.size(); i++) {
                Article article = rankedArticles.get(i);
                String emoji = getNumberEmoji(i + 1);
                
                digest.append(emoji).append(" ").append(escapeHtml(article.getTitle())).append("\n");
                
                // Show Chinese title if available
                if (article.getChineseTitle() != null && !article.getChineseTitle().isEmpty()) {
                    digest.append("   中文标题: ").append(escapeHtml(article.getChineseTitle())).append("\n");
                }
                
                if (article.getSource() != null && !article.getSource().isEmpty()) {
                    digest.append("   Source: ").append(escapeHtml(article.getSource())).append("\n");
                }
                
                if (article.getPublishTime() != null) {
                    digest.append("   Published: ").append(DATE_FORMATTER.format(article.getPublishTime())).append("\n");
                }
                
                digest.append("   Link: ").append(article.getLink()).append("\n\n");
            }
        }
        
        // Footer
        digest.append("---\n");
        digest.append("Generated by OPML RSS Trending Monitor | 由 OPML RSS 趋势监控器生成\n");
        
        logger.info("Generated digest with {} trending articles", rankedArticles.size());
        
        return digest.toString();
    }
    
    private String getNumberEmoji(int number) {
        return switch (number) {
            case 1 -> "1️⃣";
            case 2 -> "2️⃣";
            case 3 -> "3️⃣";
            case 4 -> "4️⃣";
            case 5 -> "5️⃣";
            case 6 -> "6️⃣";
            case 7 -> "7️⃣";
            case 8 -> "8️⃣";
            case 9 -> "9️⃣";
            case 10 -> "🔟";
            default -> number + ".";
        };
    }
    
    /**
     * Escape HTML special characters to prevent Telegram HTML parsing errors.
     * Characters like <, >, &, " need to be escaped when using HTML parse mode.
     */
    private String escapeHtml(String text) {
        if (text == null) {
            return "";
        }
        
        StringBuilder escaped = new StringBuilder();
        for (char c : text.toCharArray()) {
            switch (c) {
                case '<':
                    escaped.append("&lt;");
                    break;
                case '>':
                    escaped.append("&gt;");
                    break;
                case '&':
                    escaped.append("&amp;");
                    break;
                case '"':
                    escaped.append("&quot;");
                    break;
                default:
                    escaped.append(c);
            }
        }
        return escaped.toString();
    }
}
